# docker-compose.yml


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    volumes:
      - ./backend:/app
      # - backend_db:/app/db
    ports:
      - "8000:8000"
 
  # frontend:
  #   build:
  #     context: ./frontend 
  #     dockerfile: Dockerfile
  #   container_name: react-frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000" 
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - VITE_HOST=0.0.0.0

# volumes:
#   backend_db: