# Generated by Django 5.1 on 2024-09-03 14:24

import backend.cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('year', models.IntegerField(validators=[backend.cars.models.validate_year])),
                ('picture', models.URLField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
