# Generated by Django 5.1 on 2024-10-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='value',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
